spring.application.name=apifds20261

# Active profile (dev / prod)
spring.profiles.active=dev

# JWT
jwt.secret=MiClaveSecretaParaJWT2026HotelGestionSeguraSuperSegura
jwt.expiration=86400000

# Logging
logging.level.org.springframework=INFO

# Swagger UI & API Docs
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs
